/*
 * 윤이 수학 — 학습 콘텐츠
 * ------------------------------------------------------------
 * 아빠가 직접 고치는 파일이에요.
 *  - units: 1학년 11개 + 2학년 12개 단원 (v0.5.0). ready:true 인 단원만 앱에서 공부할 수 있어요. sem = 학년-학기
 *    단원 순서를 바꾸려면 이 배열의 순서만 바꾸면 돼요. (id는 바꾸지 마세요 — 진도 기록이 id로 저장돼요)
 *  - days: 하루치 구성. concept = 개념 카드, items = 문제 {g: 문제 종류, n: 개수, p: 옵션}
 *    challenge:true 인 날은 "단원 마무리 도전" (10문제, 8개 이상 맞히면 스티커)
 *  - 문제 종류(g): countTens(몇십) count(몇십몇 세기) seq(수의 순서) nextPrev(1 큰 수·1 작은 수)
 *    compare(더 큰 수) evenOdd(짝수·홀수) join(모으기) split(가르기, 10칸 상자에 넣기)
 *    calc(계산, 숫자 패드) story(이야기 문제)
 *  - calc/story의 kind: small(작은 수) make10(10 만들기) from10(10에서 빼기) three(세 수) three10(10 만들어 세 수)
 *    tenPlus(10과 몇) tens(몇십±몇십) tensOnes(몇십+몇) twoOne(몇십몇±몇) two(몇십몇±몇십몇)
 *    carry(받아올림 덧셈) borrow(받아내림 뺄셈) mixAll(섞기)
 *  - v0.5.0 문제 종류: shape(모양·도형 p.level 1·2, ask name/corner/count) clock(시계 p.step 60·30·5·1, ask read/after/before/min/day)
 *    pattern(규칙 p.kind shape/num/mul) bigNum(세·네 자리 수 p.digits, ask hund/make/place/skip/cmp/read)
 *    length(길이 ask ruler/mcm/add) sortCount(분류·표·그래프 ask count/most/least/total, chart) mulWord(묶어 세기·몇의 몇 배)
 *    calc/story kind 추가: carry2·borrow2(받아올림·받아내림 두 자리) threeBig(두 자리 세 수) blank(□ 구하기) mul(곱셈구구 dans) mulBlank div(나눗셈) mul2 div2 d1 big2 big3 mix4
 *  - explain(설명하기): { q, ans, choices?(보기), unit?, hint?, model } — 윤이가 숫자 패드·보기로 정답을 넣으면 model 설명을 보여줘요 (v0.5.0, 말하기 대신)
 *  - 글 속 숫자는 앱이 읽기 쉬운 말로 바꿔 읽어요 (8+5 → 팔 더하기 오, 7마리 → 일곱 마리)
 *  - 고친 뒤 sw.js 의 VERSION 과 app.js 의 APP_VERSION 을 올려야 설치된 앱에 반영돼요.
 */
window.CONTENT = {
  units: [
    { id: '1-1', sem: '1-1', title: '9까지의 수', icon: '🐞', sticker: '🐞', ready: false, plan: 'v0.3' },
    { id: '1-2', sem: '1-1', title: '여러 가지 모양', icon: '📦', sticker: '🤖', ready: false, plan: 'v0.3' },
    { id: '1-3', sem: '1-1', title: '덧셈과 뺄셈', icon: '🐟', sticker: '🐟', ready: false, plan: 'v0.3' },
    { id: '1-4', sem: '1-1', title: '비교하기', icon: '🐳', sticker: '🐳', ready: false, plan: 'v0.3' },
    { id: '1-5', sem: '1-1', title: '50까지의 수', icon: '🐜', sticker: '🐜', ready: false, plan: 'v0.3' },
    {
      id: '2-1', sem: '1-2', title: '100까지의 수', icon: '💯', sticker: '🚀', ready: true,
      mission: '집에 있는 콩이나 블록을 10개씩 묶어서 모두 몇 개인지 세어 봐요. 현이한테도 알려줘요!',
      days: [
        { title: '몇십 알아보기',
          concept: [
            { pic: '🐜', title: '10개씩 묶음', text: '개미가 10마리씩 줄을 섰어요. 10개씩 묶음 6개는 60이에요. 육십, 또는 예순이라고 읽어요.', vis: { tens: 60 } },
            { pic: '💯', title: '몇십 읽기', text: '70은 칠십, 일흔. 80은 팔십, 여든. 90은 구십, 아흔. 10개씩 묶음 10개는 100, 백이에요!' },
          ],
          items: [{ g: 'countTens', n: 3 }, { g: 'seq', n: 2, p: { step: 10 } }, { g: 'compare', n: 1, p: { tens: true } }] },
        { title: '99까지 세기',
          concept: [{ pic: '🐟', title: '묶음과 낱개', text: '10개씩 묶음 7개와 낱개 3개는 73이에요. 칠십삼, 또는 일흔셋이라고 읽어요.', vis: { tens: 73 } }],
          items: [{ g: 'count', n: 4 }, { g: 'seq', n: 2 }] },
        { title: '수의 순서',
          concept: [{ pic: '🚂', title: '1 큰 수, 1 작은 수', text: '1 큰 수는 바로 뒤의 수, 1 작은 수는 바로 앞의 수예요. 99보다 1 큰 수는 100이에요!', vis: { line: [97, 100] } }],
          items: [{ g: 'seq', n: 2 }, { g: 'nextPrev', n: 3 }, { g: 'seq', n: 1, p: { top: true } }] },
        { title: '수의 크기 비교',
          concept: [{ pic: '⚖️', title: '어느 수가 더 클까?', text: '10개씩 묶음이 많은 쪽이 더 커요. 묶음 수가 같으면, 낱개가 많은 쪽이 더 커요.' }],
          items: [{ g: 'compare', n: 5 }, { g: 'nextPrev', n: 1 }] },
        { title: '짝수와 홀수',
          concept: [{ pic: '🦋', title: '짝꿍 찾기', text: '둘씩 짝을 지을 때 남는 것이 없으면 짝수, 하나가 남으면 홀수예요. 2, 4, 6, 8, 10은 짝수!', vis: { pairs: 7 } }],
          items: [{ g: 'evenOdd', n: 5 }, { g: 'count', n: 1 }] },
        { title: '단원 마무리 도전', challenge: true,
          items: [{ g: 'countTens', n: 1 }, { g: 'count', n: 2 }, { g: 'seq', n: 2 }, { g: 'nextPrev', n: 1 }, { g: 'compare', n: 2 }, { g: 'evenOdd', n: 2 }] },
      ],
      explain: [
        { q: '57하고 75 중에 어느 게 더 커?', ans: 75, choices: [57, 75], model: '10개씩 묶음이 7개인 75가 더 커요!' },
        { q: '10개씩 묶음 6개와 낱개 4개는 몇이야?', ans: 64, model: '60과 4를 합해서 64예요!' },
        { q: '9는 짝수야, 홀수야?', ans: '홀수', choices: ['짝수', '홀수'], model: '둘씩 짝을 지으면 하나가 남으니까 홀수예요!' },
      ],
    },
    {
      id: '2-2', sem: '1-2', title: '덧셈과 뺄셈(1)', icon: '🎒', sticker: '🎒', ready: true,
      mission: '여행 가방 놀이! 블록 23개와 14개를 모아서 모두 몇 개인지 세어 보고, 식으로 써 봐요.',
      days: [
        { title: '(몇십몇)+(몇)',
          concept: [{ pic: '🎒', title: '낱개끼리 더해요', text: '23+4는 낱개끼리 더해요. 3+4=7, 그래서 27이에요.', vis: { tens: 23, plus: 4 } }],
          items: [{ g: 'calc', n: 4, p: { kind: 'twoOne', op: '+' } }, { g: 'story', n: 2, p: { kind: 'twoOne', op: '+' } }] },
        { title: '(몇십)+(몇십)',
          concept: [{ pic: '📦', title: '묶음끼리 더해요', text: '30+20은 10개씩 묶음 3개와 2개. 묶음이 5개니까 50이에요.', vis: { tens: 30, plus: 20 } }],
          items: [{ g: 'calc', n: 3, p: { kind: 'tens', op: '+' } }, { g: 'calc', n: 2, p: { kind: 'tensOnes' } }, { g: 'story', n: 1, p: { kind: 'tens', op: '+' } }] },
        { title: '(몇십몇)+(몇십몇)',
          concept: [{ pic: '🧳', title: '자리끼리 더해요', text: '23+14는 십의 자리끼리, 일의 자리끼리 더해요. 20+10=30, 3+4=7, 그래서 37이에요.', vis: { tens: 23, plus: 14 } }],
          items: [{ g: 'calc', n: 4, p: { kind: 'two', op: '+' } }, { g: 'story', n: 2, p: { kind: 'two', op: '+' } }] },
        { title: '(몇십몇)−(몇)',
          concept: [{ pic: '🎈', title: '낱개끼리 빼요', text: '28−5는 낱개끼리 빼요. 8−5=3, 그래서 23이에요.', vis: { tens: 28 } }],
          items: [{ g: 'calc', n: 4, p: { kind: 'twoOne', op: '-' } }, { g: 'story', n: 2, p: { kind: 'twoOne', op: '-' } }] },
        { title: '(몇십)−(몇십)',
          concept: [{ pic: '📦', title: '묶음끼리 빼요', text: '50−20은 10개씩 묶음 5개에서 2개를 빼요. 묶음 3개가 남으니까 30이에요.', vis: { tens: 50 } }],
          items: [{ g: 'calc', n: 4, p: { kind: 'tens', op: '-' } }, { g: 'story', n: 2, p: { kind: 'tens', op: '-' } }] },
        { title: '(몇십몇)−(몇십몇)',
          concept: [{ pic: '🚂', title: '자리끼리 빼요', text: '38−15는 십의 자리끼리, 일의 자리끼리 빼요. 30−10=20, 8−5=3, 그래서 23이에요.', vis: { tens: 38 } }],
          items: [{ g: 'calc', n: 4, p: { kind: 'two', op: '-' } }, { g: 'story', n: 2, p: { kind: 'two', op: '-' } }] },
        { title: '덧셈과 뺄셈 이야기',
          concept: [{ pic: '🗺️', title: '더할까, 뺄까?', text: '모두 몇 개? 하면 더하기. 남은 것은? 하면 빼기예요.' }],
          items: [{ g: 'story', n: 4, p: { kind: 'two', op: 'mix' } }, { g: 'calc', n: 2, p: { kind: 'twoOne', op: 'mix' } }] },
        { title: '단원 마무리 도전', challenge: true,
          items: [{ g: 'calc', n: 2, p: { kind: 'twoOne', op: 'mix' } }, { g: 'calc', n: 2, p: { kind: 'tens', op: 'mix' } }, { g: 'calc', n: 1, p: { kind: 'tensOnes' } }, { g: 'calc', n: 3, p: { kind: 'two', op: 'mix' } }, { g: 'story', n: 2, p: { kind: 'two', op: 'mix' } }] },
      ],
      explain: [
        { q: '23+14는 얼마야?', ans: 37, hint: '십의 자리끼리, 일의 자리끼리 더해 봐.', model: '십의 자리끼리 20+10=30, 일의 자리끼리 3+4=7. 그래서 37이에요!' },
        { q: '50−20은 얼마야?', ans: 30, hint: '10개씩 묶음 5개에서 2개를 빼 봐.', model: '10개씩 묶음 5개에서 2개를 빼면 3개. 그래서 30이에요!' },
        { q: '38−15는 얼마야?', ans: 23, hint: '십의 자리끼리, 일의 자리끼리 빼 봐.', model: '30−10=20, 8−5=3. 그래서 23이에요!' },
      ],
    },
    {
      id: '2-3', sem: '1-2', title: '여러 가지 모양', icon: '🔷', sticker: '🔷', ready: true,
      mission: '집 안에서 네모·세모·동그라미 모양을 찾아봐요. 시계는? 창문은? 삼각김밥은? 현이한테도 알려줘요!',
      days: [
        { title: '모양 찾기',
          concept: [{ pic: '🔷', title: '네모, 세모, 동그라미', text: '곧은 선 4개와 뾰족한 곳 4군데가 있으면 네모, 3군데면 세모예요. 뾰족한 곳 없이 둥글면 동그라미예요.', vis: { shapes: [4, 3, 0] } }],
          items: [{ g: 'shape', n: 6, p: { level: 1, ask: 'name' } }] },
        { title: '뾰족한 곳 세기',
          concept: [{ pic: '🔺', title: '뾰족한 곳', text: '세모는 뾰족한 곳이 3군데, 네모는 4군데예요. 동그라미는 뾰족한 곳이 없어요.', vis: { shapes: [3, 4] } }],
          items: [{ g: 'shape', n: 4, p: { level: 1, ask: 'corner' } }, { g: 'shape', n: 2, p: { level: 1, ask: 'name' } }] },
        { title: '모양 세기',
          concept: [{ pic: '🤖', title: '로봇 모양 세기', text: '로봇 그림에서 같은 모양끼리 찾아서 하나씩 세어 봐요. 센 것은 손가락으로 짚어요.' }],
          items: [{ g: 'shape', n: 4, p: { level: 1, ask: 'count' } }, { g: 'shape', n: 2, p: { level: 1, ask: 'corner' } }] },
        { title: '모양 이야기',
          concept: [{ pic: '🏠', title: '생활 속 모양', text: '창문과 책은 네모, 삼각김밥은 세모, 바퀴와 동전은 동그라미 모양이에요.' }],
          items: [{ g: 'shape', n: 3, p: { level: 1, ask: 'name' } }, { g: 'shape', n: 3, p: { level: 1, ask: 'count' } }] },
        { title: '단원 마무리 도전', challenge: true,
          items: [{ g: 'shape', n: 4, p: { level: 1, ask: 'name' } }, { g: 'shape', n: 3, p: { level: 1, ask: 'corner' } }, { g: 'shape', n: 3, p: { level: 1, ask: 'count' } }] },
      ],
      explain: [
        { q: '세모는 뾰족한 곳이 몇 군데야?', ans: 3, unit: '군데', model: '세모는 곧은 선이 3개, 뾰족한 곳이 3군데예요!' },
        { q: '동그라미에는 뾰족한 곳이 있어?', ans: '없어요', choices: ['있어요', '없어요'], model: '동그라미는 둥글어서 뾰족한 곳이 없어요!' },
        { q: '네모는 곧은 선이 몇 개야?', ans: 4, unit: '개', model: '네모는 곧은 선이 4개, 뾰족한 곳이 4군데예요!' },
      ],
    },
    {
      id: '2-4', sem: '1-2', title: '덧셈과 뺄셈(2)', icon: '🚗', sticker: '🚗', ready: true,
      mission: '주사위 3개를 굴려서 세 수를 더해 봐요. 더해서 10이 되는 두 수가 있으면 먼저 더하기!',
      days: [
        { title: '세 수의 덧셈',
          concept: [{ pic: '🚗', title: '앞에서부터 차례로', text: '2+3+4는 앞의 두 수를 먼저 더해요. 2+3=5, 5+4=9예요.' }],
          items: [{ g: 'calc', n: 5, p: { kind: 'three', op: '+' } }, { g: 'join', n: 1 }] },
        { title: '세 수의 뺄셈',
          concept: [{ pic: '🚙', title: '앞에서부터 차례로', text: '9−2−3은 앞에서부터 빼요. 9−2=7, 7−3=4예요.' }],
          items: [{ g: 'calc', n: 5, p: { kind: 'three', op: '-' } }, { g: 'story', n: 1, p: { kind: 'small', op: '-' } }] },
        { title: '10이 되는 더하기',
          concept: [{ pic: '🅿️', title: '10칸 주차장 채우기', text: '10칸 주차장에 자동차 7대가 있어요. 3대가 더 오면 가득 차요. 7과 3을 모으면 10이에요.', vis: { frame: [7, 3] } }],
          items: [{ g: 'split', n: 3, p: { total: 10 } }, { g: 'calc', n: 3, p: { kind: 'make10' } }] },
        { title: '10에서 빼기',
          concept: [{ pic: '🚕', title: '10에서 빼면', text: '10칸 주차장에서 자동차 3대가 나가면 7대가 남아요. 10−3=7이에요.', vis: { frame: [7] } }],
          items: [{ g: 'calc', n: 3, p: { kind: 'from10' } }, { g: 'split', n: 1, p: { total: 10 } }, { g: 'story', n: 2, p: { kind: 'from10' } }] },
        { title: '10을 만들어 더하기',
          concept: [{ pic: '🔟', title: '10 먼저!', text: '4+6+3은 4와 6으로 10을 먼저 만들어요. 10+3=13이에요.', vis: { frame: [4, 6] } }],
          items: [{ g: 'calc', n: 5, p: { kind: 'three10' } }, { g: 'calc', n: 1, p: { kind: 'tenPlus' } }] },
        { title: '10으로 모으기·가르기',
          concept: [{ pic: '🚌', title: '10과 몇', text: '10과 3을 모으면 13이에요. 13은 10과 3으로 가를 수 있어요.', vis: { frame: [10, 3] } }],
          items: [{ g: 'split', n: 3, p: { teen: true } }, { g: 'join', n: 3, p: { ten: true } }] },
        { title: '주차장 이야기',
          concept: [{ pic: '🗺️', title: '더할까, 뺄까?', text: '모두 몇 대? 하면 더하기. 남은 것은? 하면 빼기예요.' }],
          items: [{ g: 'story', n: 2, p: { kind: 'small', op: 'mix' } }, { g: 'story', n: 2, p: { kind: 'from10' } }, { g: 'calc', n: 2, p: { kind: 'three', op: 'mix' } }] },
        { title: '단원 마무리 도전', challenge: true,
          items: [{ g: 'calc', n: 2, p: { kind: 'three', op: 'mix' } }, { g: 'calc', n: 2, p: { kind: 'make10' } }, { g: 'calc', n: 2, p: { kind: 'from10' } }, { g: 'calc', n: 2, p: { kind: 'three10' } }, { g: 'split', n: 1, p: { teen: true } }, { g: 'story', n: 1, p: { kind: 'small', op: 'mix' } }] },
      ],
      explain: [
        { q: '3+7+5는 얼마야?', ans: 15, hint: '더해서 10이 되는 두 수를 먼저 찾아 봐.', model: '3과 7을 먼저 더해서 10을 만들어요. 10+5=15예요!' },
        { q: '10−4는 얼마야?', ans: 6, hint: '10칸 상자에서 4개를 빼 봐.', model: '10칸 상자에서 4개를 빼면 6개가 남아요!' },
        { q: '7에 몇을 더하면 10이 돼?', ans: 3, hint: '10칸 상자에 7개가 있으면 빈칸은 몇 개일까?', model: '7과 3을 모으면 10이에요. 그래서 3!' },
      ],
    },
    {
      id: '2-5', sem: '1-2', title: '시계 보기와 규칙 찾기', icon: '⏰', sticker: '⏰', ready: true,
      mission: '오늘 아침 일어난 시각, 밥 먹은 시각을 시계로 보고 아빠한테 말해 봐요. 그리고 블록으로 규칙이 있는 무늬를 만들어요!',
      days: [
        { title: '몇 시',
          concept: [{ pic: '⏰', title: '긴바늘이 12를 가리키면', text: '짧은바늘이 3, 긴바늘이 12를 가리키면 3시예요. 긴바늘이 12에 있으면 정각이에요.', vis: { clock: [3, 0] } }],
          items: [{ g: 'clock', n: 6, p: { step: 60 } }] },
        { title: '몇 시 30분',
          concept: [{ pic: '🕧', title: '긴바늘이 6을 가리키면', text: '긴바늘이 6을 가리키면 30분이에요. 짧은바늘은 두 숫자 사이에 있어요. 4와 5 사이면 4시 30분!', vis: { clock: [4, 30] } }],
          items: [{ g: 'clock', n: 6, p: { step: 30 } }] },
        { title: '시계 보기 연습',
          concept: [{ pic: '🚆', title: '하루 시간표', text: '8시에 학교 가고, 12시 30분에 점심을 먹어요. 시계를 보면 할 일을 알 수 있어요.', vis: { clock: [12, 30] } }],
          items: [{ g: 'clock', n: 3, p: { step: 60 } }, { g: 'clock', n: 3, p: { step: 30 } }] },
        { title: '무늬 규칙',
          concept: [{ pic: '🐞', title: '되풀이되는 규칙', text: '무당벌레, 나비, 무당벌레, 나비… 되풀이되는 부분을 찾으면 다음에 올 것을 알 수 있어요.' }],
          items: [{ g: 'pattern', n: 6, p: { kind: 'shape' } }] },
        { title: '수의 규칙',
          concept: [{ pic: '🔢', title: '몇씩 커질까?', text: '2, 4, 6, 8은 2씩 커져요. 그래서 다음 수는 10이에요.', vis: { line: [2, 10, 2] } }],
          items: [{ g: 'pattern', n: 5, p: { kind: 'num', steps: [1, 2, 5, 10], max: 60 } }, { g: 'pattern', n: 1, p: { kind: 'shape' } }] },
        { title: '수 배열표 규칙',
          concept: [{ pic: '🗓️', title: '수 배열표', text: '수 배열표에서 오른쪽으로 가면 1씩, 아래로 가면 10씩 커져요.' }],
          items: [{ g: 'pattern', n: 3, p: { kind: 'num', steps: [10], max: 100 } }, { g: 'pattern', n: 3, p: { kind: 'num', steps: [1, 2, 5], max: 100 } }] },
        { title: '단원 마무리 도전', challenge: true,
          items: [{ g: 'clock', n: 3, p: { step: 60 } }, { g: 'clock', n: 3, p: { step: 30 } }, { g: 'pattern', n: 2, p: { kind: 'shape' } }, { g: 'pattern', n: 2, p: { kind: 'num', steps: [2, 5, 10], max: 60 } }] },
      ],
      explain: [
        { q: '짧은바늘이 3, 긴바늘이 12를 가리키면 몇 시야?', ans: 3, unit: '시', model: '긴바늘이 12에 있으니까 정각! 짧은바늘이 3이니까 3시예요!' },
        { q: '2, 4, 6, 8 다음은 뭐야?', ans: 10, hint: '몇씩 커지는지 봐.', model: '2씩 커지는 규칙이에요. 8+2=10이에요!' },
        { q: '긴바늘이 6을 가리키면 몇 분이야?', ans: 30, unit: '분', model: '긴바늘이 6을 가리키면 30분이에요!' },
      ],
    },
    {
      id: '2-6', sem: '1-2', title: '덧셈과 뺄셈(3)', icon: '🧪', sticker: '🧪', ready: true,
      mission: '과자 13개로 실험! 5개를 먹으면 몇 개 남을까? 먼저 식으로 맞혀 보고, 진짜로 세어 봐요 🍪',
      days: [
        { title: '10을 만들어 더하기',
          concept: [{ pic: '🧪', title: '가르고 10 만들기', text: '8+5는 5를 2와 3으로 갈라요. 8+2=10, 10+3=13이에요.', vis: { frame: [8, 5] } }],
          items: [{ g: 'calc', n: 4, p: { kind: 'carry' } }, { g: 'split', n: 2, p: { total: 10, big: true } }] },
        { title: '여러 가지 방법으로 더하기',
          concept: [{ pic: '🔬', title: '앞 수를 갈라도 돼요', text: '4+9는 4를 3과 1로 갈라요. 1+9=10, 10+3=13이에요.', vis: { frame: [9, 4] } }],
          items: [{ g: 'calc', n: 4, p: { kind: 'carry' } }, { g: 'story', n: 2, p: { kind: 'carry' } }] },
        { title: '덧셈 연습',
          concept: [{ pic: '🧫', title: '규칙이 보여요', text: '9+2=11, 9+3=12, 9+4=13. 더하는 수가 1 커지면, 답도 1 커져요.' }],
          items: [{ g: 'calc', n: 4, p: { kind: 'carry' } }, { g: 'story', n: 2, p: { kind: 'carry' } }] },
        { title: '10에서 빼고 더하기',
          concept: [{ pic: '🧲', title: '10에서 빼요', text: '13−5는 13을 10과 3으로 갈라요. 10−5=5, 5+3=8이에요.', vis: { frame: [10, 3] } }],
          items: [{ g: 'calc', n: 4, p: { kind: 'borrow' } }, { g: 'calc', n: 2, p: { kind: 'from10' } }] },
        { title: '빼는 수 가르기',
          concept: [{ pic: '⚗️', title: '두 번에 나눠 빼기', text: '13−5는 5를 3과 2로 갈라요. 13−3=10, 10−2=8이에요.', vis: { frame: [10, 3] } }],
          items: [{ g: 'calc', n: 4, p: { kind: 'borrow' } }, { g: 'story', n: 2, p: { kind: 'borrow' } }] },
        { title: '뺄셈 연습',
          concept: [{ pic: '🌋', title: '규칙이 보여요', text: '15−6=9, 15−7=8, 15−8=7. 빼는 수가 1 커지면, 답은 1 작아져요.' }],
          items: [{ g: 'calc', n: 4, p: { kind: 'borrow' } }, { g: 'story', n: 2, p: { kind: 'borrow' } }] },
        { title: '과학실험 이야기',
          concept: [{ pic: '🗺️', title: '더할까, 뺄까?', text: '모두 몇 개? 하면 더하기. 남은 것은? 하면 빼기예요.' }],
          items: [{ g: 'story', n: 2, p: { kind: 'carry' } }, { g: 'story', n: 2, p: { kind: 'borrow' } }, { g: 'calc', n: 2, p: { kind: 'carry' } }] },
        { title: '단원 마무리 도전', challenge: true,
          items: [{ g: 'calc', n: 4, p: { kind: 'carry' } }, { g: 'calc', n: 4, p: { kind: 'borrow' } }, { g: 'story', n: 1, p: { kind: 'carry' } }, { g: 'story', n: 1, p: { kind: 'borrow' } }] },
      ],
      explain: [
        { q: '8+5는 얼마야?', ans: 13, hint: '5를 2와 3으로 갈라서 10을 먼저 만들어 봐.', model: '5를 2와 3으로 갈라요. 8+2=10, 10+3=13이에요!' },
        { q: '13−5는 얼마야?', ans: 8, hint: '13을 10과 3으로 갈라 봐.', model: '13을 10과 3으로 갈라요. 10−5=5, 5+3=8이에요!' },
        { q: '9+6은 얼마야?', ans: 15, hint: '6을 1과 5로 갈라서 10을 먼저 만들어 봐.', model: '6을 1과 5로 갈라요. 9+1=10, 10+5=15예요!' },
      ],
    },

    /* ================= 2학년 1학기 (v0.5.0) ================= */
    {
      id: '3-1', sem: '2-1', title: '세 자리 수', icon: '🏰', sticker: '🏰', ready: true,
      mission: '집에 있는 책 쪽수나 아파트 호수처럼 세 자리 수를 찾아서 읽어 봐요. 백의 자리 숫자는 무엇일까요?',
      days: [
        { title: '백, 몇백',
          concept: [{ pic: '💯', title: '100 알아보기', text: '10개씩 묶음 10개는 100이에요. 백이라고 읽어요. 100이 3개이면 300, 삼백이에요.' }],
          items: [{ g: 'bigNum', n: 4, p: { digits: 3, ask: 'hund' } }, { g: 'bigNum', n: 2, p: { digits: 3, ask: 'make' } }] },
        { title: '세 자리 수 쓰고 읽기',
          concept: [{ pic: '🏰', title: '백, 십, 일', text: '100이 2개, 10이 4개, 1이 7개이면 247이에요. 이백사십칠이라고 읽어요.', vis: { places: [2, 4, 7] } }],
          items: [{ g: 'bigNum', n: 3, p: { digits: 3, ask: 'make' } }, { g: 'bigNum', n: 3, p: { digits: 3, ask: 'read' } }] },
        { title: '자릿값',
          concept: [{ pic: '🔍', title: '숫자가 나타내는 값', text: '352에서 3은 백의 자리라서 300, 5는 십의 자리라서 50, 2는 일의 자리라서 2를 나타내요.' }],
          items: [{ g: 'bigNum', n: 5, p: { digits: 3, ask: 'place' } }, { g: 'bigNum', n: 1, p: { digits: 3, ask: 'make' } }] },
        { title: '뛰어 세기',
          concept: [{ pic: '🦘', title: '100씩, 10씩, 1씩', text: '100씩 뛰어 세면 백의 자리 숫자가 1씩 커져요. 300, 400, 500!', vis: { line: [300, 600, 100] } }],
          items: [{ g: 'bigNum', n: 5, p: { digits: 3, ask: 'skip' } }, { g: 'bigNum', n: 1, p: { digits: 3, ask: 'read' } }] },
        { title: '수의 크기 비교',
          concept: [{ pic: '⚖️', title: '높은 자리부터', text: '백의 자리부터 비교해요. 같으면 십의 자리, 또 같으면 일의 자리를 비교해요.' }],
          items: [{ g: 'bigNum', n: 5, p: { digits: 3, ask: 'cmp' } }, { g: 'bigNum', n: 1, p: { digits: 3, ask: 'place' } }] },
        { title: '단원 마무리 도전', challenge: true,
          items: [{ g: 'bigNum', n: 1, p: { digits: 3, ask: 'hund' } }, { g: 'bigNum', n: 2, p: { digits: 3, ask: 'make' } }, { g: 'bigNum', n: 2, p: { digits: 3, ask: 'place' } }, { g: 'bigNum', n: 2, p: { digits: 3, ask: 'skip' } }, { g: 'bigNum', n: 2, p: { digits: 3, ask: 'cmp' } }, { g: 'bigNum', n: 1, p: { digits: 3, ask: 'read' } }] },
      ],
      explain: [
        { q: '100이 3개, 10이 5개, 1이 2개이면 얼마야?', ans: 352, model: '백의 자리 3, 십의 자리 5, 일의 자리 2. 그래서 352예요!' },
        { q: '468에서 6은 얼마를 나타내?', ans: 60, choices: [6, 60, 600], model: '6은 십의 자리 숫자라서 60을 나타내요!' },
        { q: '415하고 451 중에 어느 게 더 커?', ans: 451, choices: [415, 451], model: '백의 자리는 같고, 십의 자리가 5인 451이 더 커요!' },
      ],
    },
    {
      id: '3-2', sem: '2-1', title: '여러 가지 도형', icon: '🔺', sticker: '🔺', ready: true,
      mission: '색종이를 접고 잘라서 삼각형, 사각형, 오각형을 만들어 봐요. 변과 꼭짓점을 세어 초록이한테 알려줘요!',
      days: [
        { title: '원',
          concept: [{ pic: '⭕', title: '원', text: '동그란 모양을 원이라고 해요. 원은 곧은 선도, 뾰족한 곳도 없어요. 어느 쪽에서 봐도 똑같이 동그래요.', vis: { shapes: [0] } }],
          items: [{ g: 'shape', n: 5, p: { level: 2, ask: 'name' } }] },
        { title: '삼각형과 사각형',
          concept: [{ pic: '🔺', title: '변과 꼭짓점', text: '곧은 선을 변, 두 변이 만나는 점을 꼭짓점이라고 해요. 변이 3개면 삼각형, 4개면 사각형이에요.', vis: { shapes: [3, 4] } }],
          items: [{ g: 'shape', n: 3, p: { level: 2, ask: 'name' } }, { g: 'shape', n: 3, p: { level: 2, ask: 'corner' } }] },
        { title: '오각형과 육각형',
          concept: [{ pic: '🐝', title: '벌집은 육각형', text: '변이 5개면 오각형, 6개면 육각형이에요. 벌집의 방 하나하나가 육각형이에요!', vis: { shapes: [5, 6] } }],
          items: [{ g: 'shape', n: 3, p: { level: 2, ask: 'name' } }, { g: 'shape', n: 3, p: { level: 2, ask: 'corner' } }] },
        { title: '도형 세기',
          concept: [{ pic: '🧩', title: '칠교판 놀이', text: '칠교판 조각은 삼각형 5개와 사각형 2개예요. 같은 도형끼리 모아서 세어 봐요.' }],
          items: [{ g: 'shape', n: 4, p: { level: 2, ask: 'count' } }, { g: 'shape', n: 2, p: { level: 2, ask: 'corner' } }] },
        { title: '단원 마무리 도전', challenge: true,
          items: [{ g: 'shape', n: 4, p: { level: 2, ask: 'name' } }, { g: 'shape', n: 3, p: { level: 2, ask: 'corner' } }, { g: 'shape', n: 3, p: { level: 2, ask: 'count' } }] },
      ],
      explain: [
        { q: '삼각형은 꼭짓점이 몇 개야?', ans: 3, unit: '개', model: '삼각형은 변이 3개, 꼭짓점이 3개예요!' },
        { q: '육각형은 변이 몇 개야?', ans: 6, unit: '개', model: '육각형은 변이 6개, 꼭짓점도 6개예요. 벌집 모양!' },
        { q: '원에는 꼭짓점이 몇 개야?', ans: 0, unit: '개', model: '원은 둥글어서 꼭짓점이 없어요. 0개예요!' },
      ],
    },
    {
      id: '3-3', sem: '2-1', title: '덧셈과 뺄셈', icon: '🚀', sticker: '🚀', ready: true,
      mission: '마트 놀이! 27원짜리 사탕과 15원짜리 젤리를 사면 모두 얼마일까요? 동전 블록으로 계산해 봐요.',
      days: [
        { title: '받아올림 (두 자리)+(한 자리)',
          concept: [{ pic: '🚀', title: '10은 올려요', text: '27+5는 일의 자리끼리 7+5=12. 10은 십의 자리로 올려요. 그래서 32예요.', vis: { tens: 27, plus: 5 } }],
          items: [{ g: 'calc', n: 5, p: { kind: 'carry2', one: true } }, { g: 'story', n: 1, p: { kind: 'carry2', one: true, op: '+' } }] },
        { title: '받아올림 (두 자리)+(두 자리)',
          concept: [{ pic: '🛸', title: '자리끼리 더하고 올리기', text: '38+25는 8+5=13, 3을 쓰고 10은 올려요. 30+20+10=60, 그래서 63이에요.', vis: { tens: 38, plus: 25 } }],
          items: [{ g: 'calc', n: 5, p: { kind: 'carry2', one: false } }, { g: 'story', n: 1, p: { kind: 'carry2', one: false, op: '+' } }] },
        { title: '받아내림 (두 자리)−(한 자리)',
          concept: [{ pic: '🪐', title: '10을 내려요', text: '32−5는 2에서 5를 뺄 수 없어요. 십의 자리에서 10을 받아내려 12−5=7. 그래서 27이에요.', vis: { tens: 32 } }],
          items: [{ g: 'calc', n: 5, p: { kind: 'borrow2', one: true } }, { g: 'story', n: 1, p: { kind: 'borrow2', one: true, op: '-' } }] },
        { title: '받아내림 (두 자리)−(두 자리)',
          concept: [{ pic: '🌍', title: '받아내리고 빼기', text: '52−27은 12−7=5, 40−20=20. 그래서 25예요.', vis: { tens: 52 } }],
          items: [{ g: 'calc', n: 5, p: { kind: 'borrow2', one: false } }, { g: 'story', n: 1, p: { kind: 'borrow2', one: false, op: '-' } }] },
        { title: '세 수의 계산',
          concept: [{ pic: '🧑‍🚀', title: '앞에서부터 차례로', text: '25+18−13은 앞의 두 수부터 계산해요. 25+18=43, 43−13=30이에요.' }],
          items: [{ g: 'calc', n: 5, p: { kind: 'threeBig', op: 'mix' } }, { g: 'calc', n: 1, p: { kind: 'carry2' } }] },
        { title: '□가 있는 식',
          concept: [{ pic: '🔭', title: '덧셈과 뺄셈의 관계', text: '15+□=42에서 □는 42−15로 구해요. 42−15=27이니까 □는 27이에요.' }],
          items: [{ g: 'calc', n: 5, p: { kind: 'blank', op: 'mix' } }, { g: 'calc', n: 1, p: { kind: 'borrow2' } }] },
        { title: '우주 여행 이야기',
          concept: [{ pic: '🗺️', title: '더할까, 뺄까?', text: '모두 몇 개? 하면 더하기. 남은 것은? 하면 빼기예요.' }],
          items: [{ g: 'story', n: 2, p: { kind: 'carry2', op: '+' } }, { g: 'story', n: 2, p: { kind: 'borrow2', op: '-' } }, { g: 'calc', n: 2, p: { kind: 'big2', op: 'mix' } }] },
        { title: '단원 마무리 도전', challenge: true,
          items: [{ g: 'calc', n: 3, p: { kind: 'carry2' } }, { g: 'calc', n: 3, p: { kind: 'borrow2' } }, { g: 'calc', n: 2, p: { kind: 'threeBig', op: 'mix' } }, { g: 'calc', n: 1, p: { kind: 'blank', op: 'mix' } }, { g: 'story', n: 1, p: { kind: 'carry2', op: '+' } }] },
      ],
      explain: [
        { q: '38+25는 얼마야?', ans: 63, hint: '일의 자리부터 더하고, 10이 넘으면 올려 봐.', model: '8+5=13, 3을 쓰고 10은 올려요. 30+20+10=60, 그래서 63이에요!' },
        { q: '52−27은 얼마야?', ans: 25, hint: '2에서 7을 뺄 수 없으면 10을 받아내려 봐.', model: '10을 받아내려서 12−7=5, 40−20=20. 그래서 25예요!' },
        { q: '15+□=42에서 □는 얼마야?', ans: 27, hint: '42에서 15를 빼 봐.', model: '42−15=27이니까 □는 27이에요!' },
      ],
    },
    {
      id: '3-4', sem: '2-1', title: '길이 재기', icon: '📏', sticker: '📏', ready: true,
      mission: '자로 연필, 지우개, 숟가락의 길이를 재 봐요. 가장 긴 것은 몇 cm일까요?',
      days: [
        { title: '1cm 알기',
          concept: [{ pic: '📏', title: '1cm', text: '자의 작은 눈금 한 칸이 1cm예요. 1cm가 5번이면 5cm예요. 일 센티미터라고 읽어요.', vis: { ruler: [0, 5] } }],
          items: [{ g: 'length', n: 6, p: { ask: 'ruler', max: 8 } }] },
        { title: '자로 재기',
          concept: [{ pic: '✏️', title: '0에 맞춰요', text: '물건의 한쪽 끝을 자의 0에 맞추고, 다른 쪽 끝의 눈금을 읽어요.', vis: { ruler: [0, 7] } }],
          items: [{ g: 'length', n: 6, p: { ask: 'ruler', max: 12 } }] },
        { title: '0이 아닌 곳에서 재기',
          concept: [{ pic: '🐛', title: '몇 칸일까?', text: '애벌레가 2에서 7까지 있으면 1cm가 5번이에요. 그래서 5cm예요.', vis: { ruler: [2, 5] } }],
          items: [{ g: 'length', n: 4, p: { ask: 'ruler', shift: true, max: 8 } }, { g: 'length', n: 2, p: { ask: 'ruler', max: 12 } }] },
        { title: '단원 마무리 도전', challenge: true,
          items: [{ g: 'length', n: 6, p: { ask: 'ruler', max: 12 } }, { g: 'length', n: 4, p: { ask: 'ruler', shift: true, max: 8 } }] },
      ],
      explain: [
        { q: '자의 작은 눈금 한 칸은 몇 cm야?', ans: 1, unit: 'cm', model: '작은 눈금 한 칸이 1cm예요!' },
        { q: '3에서 8까지면 몇 cm야?', ans: 5, unit: 'cm', hint: '3부터 1cm가 몇 번인지 세어 봐.', model: '1cm가 5번이니까 5cm예요!' },
        { q: '길이를 잴 때 물건 끝을 자의 몇에 맞춰?', ans: 0, model: '한쪽 끝을 0에 맞추고 다른 쪽 끝 눈금을 읽어요!' },
      ],
    },
    {
      id: '3-5', sem: '2-1', title: '분류하기', icon: '🗂️', sticker: '🗂️', ready: true,
      mission: '장난감을 정리해요! 로봇, 자동차, 공룡으로 나누어 담고 각각 몇 개인지 세어 봐요.',
      days: [
        { title: '기준에 따라 나누기',
          concept: [{ pic: '🗂️', title: '분류하기', text: '곤충끼리, 바다생물끼리처럼 같은 것끼리 나누는 것을 분류라고 해요. 누가 해도 결과가 같은 기준으로 나눠요.' }],
          items: [{ g: 'sortCount', n: 6, p: { ask: 'count' } }] },
        { title: '분류하고 세기',
          concept: [{ pic: '🦀', title: '세어서 비교하기', text: '종류별로 나누어 세면 어느 것이 가장 많은지 한눈에 알 수 있어요.' }],
          items: [{ g: 'sortCount', n: 3, p: { ask: 'count', kinds: 4 } }, { g: 'sortCount', n: 3, p: { ask: 'most' } }] },
        { title: '단원 마무리 도전', challenge: true,
          items: [{ g: 'sortCount', n: 6, p: { ask: 'count' } }, { g: 'sortCount', n: 4, p: { ask: 'most' } }] },
      ],
      explain: [
        { q: '개미, 나비, 물고기 중에 곤충이 아닌 것은?', ans: '물고기', choices: ['개미', '나비', '물고기'], model: '개미와 나비는 곤충, 물고기는 바다생물이에요!' },
        { q: '곤충 3마리, 바다생물 5마리면 모두 몇 마리야?', ans: 8, unit: '마리', model: '3+5=8, 모두 8마리예요!' },
      ],
    },
    {
      id: '3-6', sem: '2-1', title: '곱셈', icon: '✖️', sticker: '🐙', ready: true,
      mission: '문어 다리는 8개! 문어 2마리, 3마리의 다리는 모두 몇 개일까요? 블록으로 묶어서 세어 봐요.',
      days: [
        { title: '묶어 세기',
          concept: [{ pic: '🍓', title: '몇씩 몇 묶음', text: '딸기가 3개씩 4묶음 있어요. 3, 6, 9, 12. 모두 12개예요.', vis: { groups: [3, 4] } }],
          items: [{ g: 'mulWord', n: 6, p: { style: 'group', dans: [2, 3, 4, 5] } }] },
        { title: '몇의 몇 배',
          concept: [{ pic: '🐞', title: '배', text: '3씩 4묶음은 3의 4배예요. 3의 4배는 12예요.', vis: { groups: [3, 4] } }],
          items: [{ g: 'mulWord', n: 5, p: { style: 'times', dans: [2, 3, 4, 5] } }, { g: 'mulWord', n: 1, p: { style: 'group' } }] },
        { title: '곱셈식',
          concept: [{ pic: '✖️', title: '곱하기', text: '3의 4배를 3×4=12라고 써요. 삼 곱하기 사는 십이라고 읽어요.', vis: { groups: [3, 4] } }],
          items: [{ g: 'calc', n: 5, p: { kind: 'mul', dans: [2, 3, 4, 5], bmax: 5 } }, { g: 'mulWord', n: 1, p: { style: 'times' } }] },
        { title: '곱셈 이야기',
          concept: [{ pic: '🐙', title: '곱셈으로 세기', text: '문어 한 마리의 다리는 8개. 문어 2마리면 8×2=16, 다리가 16개예요.' }],
          items: [{ g: 'story', n: 4, p: { kind: 'mul', dans: [2, 3, 4, 5, 6], bmax: 5, op: '×' } }, { g: 'calc', n: 2, p: { kind: 'mul', dans: [2, 3, 4, 5], bmax: 5 } }] },
        { title: '단원 마무리 도전', challenge: true,
          items: [{ g: 'mulWord', n: 3, p: { style: 'group' } }, { g: 'mulWord', n: 3, p: { style: 'times' } }, { g: 'calc', n: 3, p: { kind: 'mul', dans: [2, 3, 4, 5], bmax: 5 } }, { g: 'story', n: 1, p: { kind: 'mul', dans: [2, 3, 4, 5], bmax: 5, op: '×' } }] },
      ],
      explain: [
        { q: '4씩 3묶음은 모두 몇 개야?', ans: 12, unit: '개', hint: '4, 8, 그다음은?', model: '4, 8, 12! 4의 3배는 12, 4×3=12예요!' },
        { q: '2의 5배는 얼마야?', ans: 10, model: '2+2+2+2+2=10. 2×5=10이에요!' },
        { q: '3×4는 얼마야?', ans: 12, model: '3씩 4묶음이니까 3, 6, 9, 12. 그래서 12예요!' },
      ],
    },

    /* ================= 2학년 2학기 (v0.5.0) ================= */
    {
      id: '4-1', sem: '2-2', title: '네 자리 수', icon: '🏯', sticker: '🏯', ready: true,
      mission: '달력에서 올해 연도(네 자리 수)를 찾아 읽어 봐요. 천의 자리 숫자는 무엇일까요?',
      days: [
        { title: '천, 몇천',
          concept: [{ pic: '🏯', title: '1000 알아보기', text: '100이 10개이면 1000이에요. 천이라고 읽어요. 1000이 3개이면 3000, 삼천이에요.' }],
          items: [{ g: 'bigNum', n: 4, p: { digits: 4, ask: 'hund' } }, { g: 'bigNum', n: 2, p: { digits: 4, ask: 'make' } }] },
        { title: '네 자리 수 쓰고 읽기',
          concept: [{ pic: '🔢', title: '천, 백, 십, 일', text: '1000이 2개, 100이 5개, 10이 3개, 1이 8개이면 2538이에요. 이천오백삼십팔이라고 읽어요.', vis: { places: [2, 5, 3, 8] } }],
          items: [{ g: 'bigNum', n: 3, p: { digits: 4, ask: 'make' } }, { g: 'bigNum', n: 3, p: { digits: 4, ask: 'read' } }] },
        { title: '자릿값',
          concept: [{ pic: '🔍', title: '숫자가 나타내는 값', text: '4273에서 4는 천의 자리라서 4000, 2는 백의 자리라서 200을 나타내요.' }],
          items: [{ g: 'bigNum', n: 5, p: { digits: 4, ask: 'place' } }, { g: 'bigNum', n: 1, p: { digits: 4, ask: 'read' } }] },
        { title: '뛰어 세기',
          concept: [{ pic: '🦘', title: '1000씩 뛰어 세기', text: '1000씩 뛰어 세면 천의 자리 숫자가 1씩 커져요. 2000, 3000, 4000!', vis: { line: [2000, 5000, 1000] } }],
          items: [{ g: 'bigNum', n: 5, p: { digits: 4, ask: 'skip' } }, { g: 'bigNum', n: 1, p: { digits: 4, ask: 'make' } }] },
        { title: '수의 크기 비교',
          concept: [{ pic: '⚖️', title: '천의 자리부터', text: '천의 자리부터 차례로 비교해요. 3526과 3562는 천·백의 자리가 같고, 십의 자리가 큰 3562가 더 커요.' }],
          items: [{ g: 'bigNum', n: 5, p: { digits: 4, ask: 'cmp' } }, { g: 'bigNum', n: 1, p: { digits: 4, ask: 'place' } }] },
        { title: '단원 마무리 도전', challenge: true,
          items: [{ g: 'bigNum', n: 1, p: { digits: 4, ask: 'hund' } }, { g: 'bigNum', n: 2, p: { digits: 4, ask: 'make' } }, { g: 'bigNum', n: 2, p: { digits: 4, ask: 'place' } }, { g: 'bigNum', n: 2, p: { digits: 4, ask: 'skip' } }, { g: 'bigNum', n: 2, p: { digits: 4, ask: 'cmp' } }, { g: 'bigNum', n: 1, p: { digits: 4, ask: 'read' } }] },
      ],
      explain: [
        { q: '100이 10개이면 얼마야?', ans: 1000, model: '100이 10개이면 1000, 천이에요!' },
        { q: '5382에서 3은 얼마를 나타내?', ans: 300, choices: [3, 30, 300, 3000], model: '3은 백의 자리 숫자라서 300을 나타내요!' },
        { q: '2999보다 1 큰 수는 얼마야?', ans: 3000, model: '2999 다음 수는 3000이에요!' },
      ],
    },
    {
      id: '4-2', sem: '2-2', title: '곱셈구구', icon: '🐙', sticker: '🦑', ready: true,
      mission: '곱셈구구 노래를 부르며 2단부터 9단까지 외워 봐요. 현이한테 2단을 가르쳐 줘요!',
      days: [
        { title: '2단과 5단',
          concept: [{ pic: '🦋', title: '2단, 5단', text: '2단은 2씩, 5단은 5씩 커져요. 2×3=6, 5×3=15예요.', vis: { groups: [2, 3] } }],
          items: [{ g: 'calc', n: 6, p: { kind: 'mul', dans: [2, 5] } }] },
        { title: '3단과 6단',
          concept: [{ pic: '🐞', title: '3단, 6단', text: '곤충 다리는 6개! 6단은 6씩 커져요. 6×2=12, 6×3=18이에요. 3단의 곱을 두 번 더하면 6단이에요.', vis: { groups: [6, 2] } }],
          items: [{ g: 'calc', n: 6, p: { kind: 'mul', dans: [3, 6] } }] },
        { title: '4단과 8단',
          concept: [{ pic: '🐙', title: '4단, 8단', text: '문어 다리는 8개! 8단은 8씩 커져요. 8×2=16, 8×3=24예요.', vis: { groups: [8, 2] } }],
          items: [{ g: 'calc', n: 6, p: { kind: 'mul', dans: [4, 8] } }] },
        { title: '7단',
          concept: [{ pic: '🌈', title: '7단', text: '무지개는 7가지 색! 7단은 7씩 커져요. 7×2=14, 7×3=21이에요.', vis: { groups: [7, 2] } }],
          items: [{ g: 'calc', n: 5, p: { kind: 'mul', dans: [7] } }, { g: 'calc', n: 1, p: { kind: 'mul', dans: [2, 3, 4, 5, 6, 8] } }] },
        { title: '9단',
          concept: [{ pic: '🤖', title: '9단', text: '9단은 9씩 커져요. 9×2=18, 9×3=27. 십의 자리는 1씩 커지고, 일의 자리는 1씩 작아져요!' }],
          items: [{ g: 'calc', n: 5, p: { kind: 'mul', dans: [9] } }, { g: 'calc', n: 1, p: { kind: 'mul', dans: [7] } }] },
        { title: '1단과 0의 곱',
          concept: [{ pic: '🥚', title: '1과 0', text: '1×5=5, 어떤 수에 1을 곱하면 그 수예요. 0×5=0, 5×0=0, 0에 곱하거나 0을 곱하면 0이에요.' }],
          items: [{ g: 'calc', n: 3, p: { kind: 'mul', dans: [1], bmin: 1 } }, { g: 'calc', n: 3, p: { kind: 'mul', dans: [0, 2, 3, 4, 5], bmin: 0, swap: true } }] },
        { title: '곱셈표와 □ 구하기',
          concept: [{ pic: '🔢', title: '곱셈표 규칙', text: '곱셈표에서 5단은 5씩 커져요. 3×□=15에서 □는 3단에서 15를 찾으면 5예요.' }],
          items: [{ g: 'pattern', n: 2, p: { kind: 'mul' } }, { g: 'calc', n: 4, p: { kind: 'mulBlank' } }] },
        { title: '곱셈구구 이야기',
          concept: [{ pic: '🗺️', title: '곱셈으로 풀어요', text: '똑같은 수가 여러 묶음 있으면 곱셈으로 한 번에 구해요.' }],
          items: [{ g: 'story', n: 4, p: { kind: 'mul', op: '×' } }, { g: 'calc', n: 2, p: { kind: 'mul', swap: true } }] },
        { title: '단원 마무리 도전', challenge: true,
          items: [{ g: 'calc', n: 2, p: { kind: 'mul', dans: [2, 5] } }, { g: 'calc', n: 2, p: { kind: 'mul', dans: [3, 6] } }, { g: 'calc', n: 2, p: { kind: 'mul', dans: [4, 8] } }, { g: 'calc', n: 2, p: { kind: 'mul', dans: [7, 9] } }, { g: 'calc', n: 1, p: { kind: 'mulBlank' } }, { g: 'story', n: 1, p: { kind: 'mul', op: '×' } }] },
      ],
      explain: [
        { q: '6×4는 얼마야?', ans: 24, hint: '6, 12, 18, 그다음은?', model: '6씩 4묶음! 6, 12, 18, 24. 그래서 24예요!' },
        { q: '7×0은 얼마야?', ans: 0, model: '어떤 수에 0을 곱하면 0이에요!' },
        { q: '8단은 몇씩 커져?', ans: 8, model: '8×1=8, 8×2=16. 8씩 커져요!' },
      ],
    },
    {
      id: '4-3', sem: '2-2', title: '길이 재기(m와 cm)', icon: '📐', sticker: '🦒', ready: true,
      mission: '줄자로 윤이 키와 아빠 키를 재 봐요. 몇 m 몇 cm일까요? 누가 몇 cm 더 클까요?',
      days: [
        { title: '1m 알기',
          concept: [{ pic: '📐', title: '1m=100cm', text: '100cm는 1m예요. 일 미터라고 읽어요. 1m보다 20cm 더 길면 1m 20cm, 120cm예요.' }],
          items: [{ g: 'length', n: 6, p: { ask: 'mcm' } }] },
        { title: '길이의 덧셈',
          concept: [{ pic: '🦒', title: 'm끼리, cm끼리', text: '1m 20cm+2m 50cm는 m끼리 1+2=3, cm끼리 20+50=70. 그래서 3m 70cm예요.' }],
          items: [{ g: 'length', n: 5, p: { ask: 'add' } }, { g: 'length', n: 1, p: { ask: 'mcm' } }] },
        { title: '길이 재기 연습',
          concept: [{ pic: '📏', title: '다시 자로 재기', text: '짧은 길이는 자로 cm를, 긴 길이는 줄자로 m와 cm를 재요.', vis: { ruler: [0, 9] } }],
          items: [{ g: 'length', n: 3, p: { ask: 'ruler', max: 13, shift: true } }, { g: 'length', n: 3, p: { ask: 'mcm' } }] },
        { title: '단원 마무리 도전', challenge: true,
          items: [{ g: 'length', n: 4, p: { ask: 'mcm' } }, { g: 'length', n: 4, p: { ask: 'add' } }, { g: 'length', n: 2, p: { ask: 'ruler', max: 13, shift: true } }] },
      ],
      explain: [
        { q: '1m는 몇 cm야?', ans: 100, unit: 'cm', model: '1m는 100cm예요!' },
        { q: '1m 30cm는 몇 cm야?', ans: 130, unit: 'cm', model: '1m는 100cm. 100+30=130cm예요!' },
        { q: '2m 10cm+1m 40cm는 몇 m 50cm야?', ans: 3, unit: 'm', model: 'm끼리 2+1=3, cm끼리 10+40=50. 3m 50cm예요!' },
      ],
    },
    {
      id: '4-4', sem: '2-2', title: '시각과 시간', icon: '🕰️', sticker: '🕰️', ready: true,
      mission: '오늘 하루 일어난 시각, 학교 간 시각, 잠자는 시각을 몇 시 몇 분까지 적어 봐요.',
      days: [
        { title: '몇 시 몇 분 (5분)',
          concept: [{ pic: '🕰️', title: '숫자 한 칸은 5분', text: '긴바늘이 숫자 1을 가리키면 5분, 2를 가리키면 10분이에요. 5씩 뛰어 세어요.', vis: { clock: [2, 10] } }],
          items: [{ g: 'clock', n: 6, p: { step: 5 } }] },
        { title: '몇 시 몇 분 (1분)',
          concept: [{ pic: '⏱️', title: '작은 눈금 한 칸은 1분', text: '긴바늘이 3에서 작은 눈금 2칸 더 가면 17분이에요.', vis: { clock: [5, 17] } }],
          items: [{ g: 'clock', n: 6, p: { step: 1 } }] },
        { title: '몇 시 몇 분 전',
          concept: [{ pic: '🔔', title: '몇 분 전', text: '2시 50분은 3시가 되기 10분 전이에요. 그래서 3시 10분 전이라고도 해요.', vis: { clock: [2, 50] } }],
          items: [{ g: 'clock', n: 4, p: { ask: 'before' } }, { g: 'clock', n: 2, p: { step: 5 } }] },
        { title: '1시간은 60분',
          concept: [{ pic: '🔄', title: '긴바늘 한 바퀴', text: '긴바늘이 한 바퀴 돌면 60분, 1시간이에요. 1시간 20분은 80분이에요.' }],
          items: [{ g: 'clock', n: 4, p: { ask: 'min' } }, { g: 'clock', n: 2, p: { ask: 'after', step: 60 } }] },
        { title: '걸린 시간',
          concept: [{ pic: '🚌', title: '몇 분 뒤', text: '3시 10분에서 20분 뒤는 3시 30분이에요. 긴바늘이 숫자 4칸을 가요.' }],
          items: [{ g: 'clock', n: 4, p: { ask: 'after', step: 5 } }, { g: 'clock', n: 2, p: { ask: 'after', step: 60 } }] },
        { title: '하루·1주일·1년',
          concept: [{ pic: '📅', title: '달력', text: '하루는 24시간, 1주일은 7일, 1년은 12개월이에요. 오전은 밤 12시부터 낮 12시까지, 오후는 낮 12시부터 밤 12시까지예요.' }],
          items: [{ g: 'clock', n: 6, p: { ask: 'day' } }] },
        { title: '단원 마무리 도전', challenge: true,
          items: [{ g: 'clock', n: 3, p: { step: 5 } }, { g: 'clock', n: 2, p: { step: 1 } }, { g: 'clock', n: 1, p: { ask: 'before' } }, { g: 'clock', n: 2, p: { ask: 'min' } }, { g: 'clock', n: 1, p: { ask: 'after', step: 5 } }, { g: 'clock', n: 1, p: { ask: 'day' } }] },
      ],
      explain: [
        { q: '긴바늘이 4를 가리키면 몇 분이야?', ans: 20, unit: '분', hint: '5, 10, 15, 그다음은?', model: '숫자 한 칸이 5분이니까 5, 10, 15, 20. 20분이에요!' },
        { q: '1시간은 몇 분이야?', ans: 60, unit: '분', model: '긴바늘이 한 바퀴 돌면 60분, 1시간이에요!' },
        { q: '하루는 몇 시간이야?', ans: 24, unit: '시간', model: '오전 12시간과 오후 12시간, 모두 24시간이에요!' },
      ],
    },
    {
      id: '4-5', sem: '2-2', title: '표와 그래프', icon: '📊', sticker: '📊', ready: true,
      mission: '가족에게 좋아하는 바다생물을 물어보고 표와 ○ 그래프로 나타내 봐요!',
      days: [
        { title: '표 만들기',
          concept: [{ pic: '📋', title: '표로 나타내기', text: '조사한 것을 종류별로 세어 표로 나타내면 모두 몇 명인지, 무엇이 몇 명인지 쉽게 알 수 있어요.' }],
          items: [{ g: 'sortCount', n: 3, p: { ask: 'count', chart: true } }, { g: 'sortCount', n: 3, p: { ask: 'total', chart: true } }] },
        { title: '그래프 읽기',
          concept: [{ pic: '📊', title: '○ 그래프', text: '그래프에서 ○가 가장 긴 줄이 가장 많은 것, 가장 짧은 줄이 가장 적은 것이에요.' }],
          items: [{ g: 'sortCount', n: 3, p: { ask: 'most', chart: true } }, { g: 'sortCount', n: 3, p: { ask: 'least', chart: true } }] },
        { title: '표와 그래프 연습',
          concept: [{ pic: '🐠', title: '무엇을 알 수 있을까?', text: '표는 수와 합계를 알기 쉽고, 그래프는 많고 적음을 한눈에 비교하기 쉬워요.' }],
          items: [{ g: 'sortCount', n: 2, p: { ask: 'count', chart: true, kinds: 4 } }, { g: 'sortCount', n: 2, p: { ask: 'total', chart: true, kinds: 4 } }, { g: 'sortCount', n: 2, p: { ask: 'most', chart: true, kinds: 4 } }] },
        { title: '단원 마무리 도전', challenge: true,
          items: [{ g: 'sortCount', n: 3, p: { ask: 'count', chart: true } }, { g: 'sortCount', n: 3, p: { ask: 'total', chart: true } }, { g: 'sortCount', n: 2, p: { ask: 'most', chart: true } }, { g: 'sortCount', n: 2, p: { ask: 'least', chart: true } }] },
      ],
      explain: [
        { q: '그래프에서 가장 많은 것은 어떻게 찾아?', ans: '가장 긴 줄', choices: ['가장 긴 줄', '가장 짧은 줄'], model: '○가 가장 긴 줄이 가장 많은 거예요!' },
        { q: '문어 3명, 고래 5명, 게 2명이면 모두 몇 명이야?', ans: 10, unit: '명', model: '3+5+2=10, 모두 10명이에요!' },
      ],
    },
    {
      id: '4-6', sem: '2-2', title: '규칙 찾기', icon: '🔁', sticker: '🔁', ready: true,
      mission: '달력에서 같은 요일의 날짜를 세로로 읽어 봐요. 몇씩 커지나요? 블록으로 규칙 무늬도 만들어요!',
      days: [
        { title: '무늬 규칙',
          concept: [{ pic: '🧶', title: '되풀이되는 무늬', text: '무늬에서 되풀이되는 부분을 찾으면 다음에 올 것을 알 수 있어요.' }],
          items: [{ g: 'pattern', n: 6, p: { kind: 'shape', abc: true } }] },
        { title: '덧셈표 규칙',
          concept: [{ pic: '➕', title: '덧셈표', text: '덧셈표에서 오른쪽으로 가면 1씩 커지고, 아래로 가도 1씩 커져요.' }],
          items: [{ g: 'pattern', n: 6, p: { kind: 'num', steps: [1, 2, 3, 4, 5], max: 99 } }] },
        { title: '곱셈표 규칙',
          concept: [{ pic: '✖️', title: '곱셈표', text: '곱셈표에서 4단은 4씩, 7단은 7씩 커져요. 3×5와 5×3은 같아요.' }],
          items: [{ g: 'pattern', n: 3, p: { kind: 'mul' } }, { g: 'pattern', n: 3, p: { kind: 'num', steps: [3, 4, 6, 7, 8, 9], max: 90 } }] },
        { title: '달력 규칙',
          concept: [{ pic: '📅', title: '달력', text: '달력에서 아래로 한 칸 가면 7일 뒤, 같은 요일이에요. 그래서 7씩 커져요.' }],
          items: [{ g: 'pattern', n: 6, p: { kind: 'num', steps: [7], max: 31, sub: '달력의 같은 요일 날짜예요.' } }] },
        { title: '단원 마무리 도전', challenge: true,
          items: [{ g: 'pattern', n: 3, p: { kind: 'shape', abc: true } }, { g: 'pattern', n: 3, p: { kind: 'num', steps: [2, 3, 4, 5], max: 99 } }, { g: 'pattern', n: 2, p: { kind: 'mul' } }, { g: 'pattern', n: 2, p: { kind: 'num', steps: [7], max: 31 } }] },
      ],
      explain: [
        { q: '달력에서 아래로 한 칸 가면 며칠이 커져?', ans: 7, unit: '일', model: '1주일은 7일! 아래로 한 칸 가면 7씩 커져요!' },
        { q: '3, 6, 9, 12 다음은 뭐야?', ans: 15, model: '3씩 커지는 규칙이에요. 12+3=15예요!' },
        { q: '5단은 몇씩 커져?', ans: 5, model: '5×1=5, 5×2=10. 5씩 커져요!' },
      ],
    },
  ],

  // 연산 사다리 12칸 (단원과 따로 올라가요). 1~7칸은 10칸 상자 그림을 함께, 8칸부터는 식 위주
  ladder: [
    { name: '5까지 모으기·가르기', ex: '2+3, 5−1', p: { kind: 'small', max: 5, op: 'mix' } },
    { name: '10까지 덧셈', ex: '4+5', p: { kind: 'small', max: 10, op: '+' } },
    { name: '10까지 뺄셈', ex: '9−6', p: { kind: 'small', max: 10, op: '-' } },
    { name: '10 만들기', ex: '7+□=10', p: { kind: 'make10' } },
    { name: '10에서 빼기', ex: '10−3', p: { kind: 'from10' } },
    { name: '세 수의 계산', ex: '3+4+2', p: { kind: 'three', op: 'mix' } },
    { name: '10과 몇', ex: '10+6, 16−6', p: { kind: 'tenPlus' } },
    { name: '몇십+몇, 몇십±몇십', ex: '30+5, 40+20', p: { kind: 'tensMix' } },
    { name: '받아올림 없는 두 자리', ex: '23+14, 38−15', p: { kind: 'two', op: 'mix' } },
    { name: '받아올림 있는 덧셈', ex: '8+5, 9+7', p: { kind: 'carry' } },
    { name: '받아내림 있는 뺄셈', ex: '13−5, 15−8', p: { kind: 'borrow' } },
    { name: '혼합 도전', ex: '위 유형 섞기', p: { kind: 'mixAll' } },
    // v0.5.0: 2학년 연산 (13~20칸)
    { name: '받아올림 두 자리 덧셈', ex: '27+15, 38+6', p: { kind: 'carry2' } },
    { name: '받아내림 두 자리 뺄셈', ex: '52−27, 43−8', p: { kind: 'borrow2' } },
    { name: '곱셈구구 2·5단', ex: '2×7, 5×6', p: { kind: 'mul', dans: [2, 5] } },
    { name: '곱셈구구 3·6단', ex: '3×8, 6×4', p: { kind: 'mul', dans: [3, 6] } },
    { name: '곱셈구구 4·8단', ex: '4×6, 8×7', p: { kind: 'mul', dans: [4, 8] } },
    { name: '곱셈구구 7·9단', ex: '7×8, 9×6', p: { kind: 'mul', dans: [7, 9] } },
    { name: '곱셈구구 전체', ex: '2단~9단 섞기', p: { kind: 'mul', swap: true } },
    { name: '나눗셈 도전', ex: '24÷6, 56÷8', p: { kind: 'div' } },
  ],

  // 🧮 연산 연습 (홈 화면 "연산 연습", v0.5.0). 하루 공부와 따로, 고른 연산을 count문제씩 더 풀어요.
  // p는 문제 종류(kind): d1(한 자리) big2(두 자리) big3(세 자리) carry2·borrow2(받아올림·받아내림) mul(곱셈구구, dans=단) mul2(두 자리×한 자리) div(나눗셈) div2(두 자리÷한 자리) mix4(섞기)
  drill: {
    count: 10,
    ops: [
      { id: 'add', name: '더하기', icon: '➕', sizes: [
        { id: 'd1', name: '한 자리', ex: '8+5', em: '🐞', p: { kind: 'd1', op: '+' } },
        { id: 'c2', name: '받아올림', ex: '27+15', em: '🚀', p: { kind: 'carry2' } },
        { id: 'b2', name: '두 자리', ex: '46+38, 75+59', em: '🐟', p: { kind: 'big2', op: '+' } },
        { id: 'b3', name: '세 자리', ex: '235+418', em: '🏰', p: { kind: 'big3', op: '+' } },
      ] },
      { id: 'sub', name: '빼기', icon: '➖', sizes: [
        { id: 'd1', name: '한 자리', ex: '13−5', em: '🐜', p: { kind: 'd1', op: '-' } },
        { id: 'c2', name: '받아내림', ex: '52−27', em: '🪐', p: { kind: 'borrow2' } },
        { id: 'b2', name: '두 자리', ex: '84−36', em: '🦀', p: { kind: 'big2', op: '-' } },
        { id: 'b3', name: '세 자리', ex: '642−275', em: '🏯', p: { kind: 'big3', op: '-' } },
      ] },
      { id: 'mul', name: '곱하기', icon: '✖️', sizes: [
        { id: '25', name: '2·5단', ex: '2×7, 5×6', em: '🦋', p: { kind: 'mul', dans: [2, 5] } },
        { id: '36', name: '3·6단', ex: '3×8, 6×4', em: '🐞', p: { kind: 'mul', dans: [3, 6] } },
        { id: '48', name: '4·8단', ex: '4×6, 8×7', em: '🐙', p: { kind: 'mul', dans: [4, 8] } },
        { id: '79', name: '7·9단', ex: '7×8, 9×6', em: '🌈', p: { kind: 'mul', dans: [7, 9] } },
        { id: 'all', name: '곱셈구구 전체', ex: '2단~9단', em: '🤖', p: { kind: 'mul', swap: true } },
        { id: 'big', name: '두 자리×한 자리', ex: '23×4', em: '🚀', p: { kind: 'mul2' } },
      ] },
      { id: 'div', name: '나누기', icon: '➗', sizes: [
        { id: 'e', name: '2~5로 나누기', ex: '12÷3, 20÷5', em: '🍪', p: { kind: 'div', dans: [2, 3, 4, 5] } },
        { id: 'h', name: '6~9로 나누기', ex: '42÷7, 72÷9', em: '🍩', p: { kind: 'div', dans: [6, 7, 8, 9] } },
        { id: 'all', name: '곱셈구구 전체', ex: '2~9로 나누기', em: '🤖', p: { kind: 'div' } },
        { id: 'big', name: '두 자리÷한 자리', ex: '84÷4', em: '🚀', p: { kind: 'div2' } },
      ] },
      { id: 'mix', name: '섞어서', icon: '🎲', sizes: [
        { id: 'e', name: '쉬운 섞기', ex: '한 자리 +−, 2~5단 ×÷', em: '🎲', p: { kind: 'mix4', lv: 1 } },
        { id: 'h', name: '어려운 섞기', ex: '두·세 자리 +−, 전체 ×÷', em: '🎯', p: { kind: 'mix4', lv: 2 } },
      ] },
    ],
  },

  // 이야기 문제 틀. {F} = 친구 이름(현이가·초록이가·은후가), {a}{b} = 숫자. 숫자 바로 뒤에 단위를 붙여 써요.
  // pic = 그림 이모지. 문장은 짧게 (15자 안팎)
  stories: {
    add: [
      { pic: '🐜', text: '{F} 돋보기로 개미 {a}마리를 찾았어요. {b}마리가 더 왔어요. 모두 몇 마리일까요?', unit: '마리' },
      { pic: '🐞', text: '{F} 무당벌레 {a}마리를 찾았어요. 윤이는 {b}마리를 찾았어요. 모두 몇 마리일까요?', unit: '마리' },
      { pic: '🐟', text: '바다에 물고기 {a}마리가 있어요. {b}마리가 더 헤엄쳐 왔어요. 모두 몇 마리일까요?', unit: '마리' },
      { pic: '🔮', text: '시험관에 구슬 {a}개를 넣었어요. {b}개를 더 넣었어요. 모두 몇 개일까요?', unit: '개' },
      { pic: '⚙️', text: '로봇 공장에 바퀴가 {a}개 있어요. {b}개를 더 만들었어요. 모두 몇 개일까요?', unit: '개' },
      { pic: '📷', text: '{F} 여행 사진을 {a}장 찍었어요. 윤이는 {b}장 찍었어요. 모두 몇 장일까요?', unit: '장' },
      { pic: '🐌', text: '화분에 달팽이 {a}마리가 있어요. {b}마리가 더 기어 왔어요. 모두 몇 마리일까요?', unit: '마리' },
    ],
    sub: [
      { pic: '🐟', text: '어항에 물고기가 {a}마리 있어요. {b}마리를 다른 어항으로 옮겼어요. 남은 물고기는 몇 마리일까요?', unit: '마리' },
      { pic: '🚂', text: '기차에 {a}명이 타고 있어요. 다음 역에서 {b}명이 내렸어요. 남은 사람은 몇 명일까요?', unit: '명' },
      { pic: '🦋', text: '꽃밭에 나비 {a}마리가 앉아 있어요. {b}마리가 날아갔어요. 남은 나비는 몇 마리일까요?', unit: '마리' },
      { pic: '🎈', text: '풍선이 {a}개 있어요. {b}개가 날아갔어요. 남은 풍선은 몇 개일까요?', unit: '개' },
      { pic: '⚙️', text: '{F} 로봇 부품 {a}개를 가지고 있어요. 로봇을 만드느라 {b}개를 썼어요. 남은 부품은 몇 개일까요?', unit: '개' },
      { pic: '🍪', text: '과자가 {a}개 있어요. {F} {b}개를 먹었어요. 남은 과자는 몇 개일까요?', unit: '개' },
    ],
    // 곱셈: {a} = 한 묶음의 수, {b} = 묶음 수 (v0.5.0)
    mul: [
      { pic: '🐞', text: '무당벌레 한 마리는 다리가 {a}개예요. {b}마리의 다리는 모두 몇 개일까요?', unit: '개' },
      { pic: '🐟', text: '어항 하나에 물고기가 {a}마리씩 있어요. 어항 {b}개에는 모두 몇 마리일까요?', unit: '마리' },
      { pic: '🤖', text: '{F} 로봇 한 대에 바퀴를 {a}개씩 달아요. 로봇 {b}대에는 바퀴가 모두 몇 개일까요?', unit: '개' },
      { pic: '🧪', text: '시험관 하나에 구슬을 {a}개씩 넣어요. 시험관 {b}개에는 모두 몇 개일까요?', unit: '개' },
      { pic: '🐚', text: '{F} 바닷가에서 조개를 {a}개씩 {b}번 주웠어요. 모두 몇 개일까요?', unit: '개' },
      { pic: '🚌', text: '여행 버스 한 줄에 {a}명씩 앉아요. {b}줄에는 모두 몇 명일까요?', unit: '명' },
    ],
    // 나눗셈: {a} = 전체, {b} = 나누는 수 (v0.5.0)
    div: [
      { pic: '🍪', text: '쿠키 {a}개를 {b}명이 똑같이 나누어 먹어요. 한 명이 몇 개씩 먹을까요?', unit: '개' },
      { pic: '🐟', text: '물고기 {a}마리를 어항 {b}개에 똑같이 나누어 넣어요. 어항 하나에 몇 마리씩일까요?', unit: '마리' },
      { pic: '⚙️', text: '{F} 부품 {a}개를 로봇 {b}대에 똑같이 나누어 달아요. 한 대에 몇 개씩일까요?', unit: '개' },
    ],
  },

  // 무늬 규칙 문제에 쓰는 그림과 이름 (v0.5.0)
  patternThings: [['🐞', '무당벌레'], ['🦋', '나비'], ['🐟', '물고기'], ['🐝', '벌'], ['🐌', '달팽이'], ['🦀', '게'], ['⭐', '별'], ['🚗', '자동차'], ['🤖', '로봇'], ['🐙', '문어'], ['🌸', '꽃'], ['🍎', '사과']],
  // 분류하기·표와 그래프 문제 (v0.5.0). items = [그림, 이름], unit = 셀 때 단위, chart = 그래프 제목
  sortSets: [
    { unit: '마리', chart: '친구들이 좋아하는 곤충', items: [['🐞', '무당벌레'], ['🐜', '개미'], ['🦋', '나비'], ['🐝', '벌'], ['🐛', '애벌레']] },
    { unit: '마리', chart: '친구들이 좋아하는 바다생물', items: [['🐟', '물고기'], ['🐙', '문어'], ['🦀', '게'], ['🐳', '고래'], ['🦈', '상어']] },
    { unit: '개', chart: '친구들이 좋아하는 장난감', items: [['🤖', '로봇'], ['🚗', '자동차'], ['🧩', '퍼즐'], ['⚽', '공'], ['🪁', '연']] },
    { unit: '개', chartOnly: true, chart: '친구들이 가고 싶은 여행지', items: [['🏖️', '바다'], ['⛰️', '산'], ['🏕️', '캠핑장'], ['🎡', '놀이공원'], ['🐬', '수족관']] },
  ],

  // 문제 그림에 쓰는 이모지 (셀 때)
  things: ['🐞', '🐜', '🐟', '🦋', '🐝', '🐌', '🦀', '⭐', '🔩', '🚗'],

  // 로봇 친구가 하는 말 (한국어, 짧게)
  lines: {
    praise: ['잘했어!', '멋져!', '맞았어!', '최고야!', '와, 대단해!', '정답이야!', '훌륭해!', '딱 맞았어!'],
    retry: ['다시 해볼까?', '한 번 더 생각해 볼까?'],
    showAnswer: '괜찮아! 같이 풀어 보자.',
  },

  // 함께하는 친구들 (앱 속 캐릭터). subj = 이야기 문제에서 "~가" 붙인 이름
  friends: {
    eunhoo: { name: '은후', subj: '은후가', color: '#ffb74d', role: '같이 문제 푸는 친구' },
    chorok: { name: '초록', subj: '초록이가', call: '초록이', color: '#66bb6a', role: '윤이가 가르쳐주는 동생 (친척동생)' },
    hyun: { name: '현', subj: '현이가', call: '현이', color: '#64b5f6', role: '윤이가 가르쳐주는 동생 (친동생)' },
  },
};
